### ISSUE TITLE
POSIX file permissions problem in Windows

### ISSUE THREAD

**Issue by inigo** [webjars/webjars-locator-core#123]
Using webjars-locator-core 0.54 via Play 2.9, running Windows on NTFS, I encounter an `UnsupportedOperationException` when trying to extract webjars. The problem seems to be from using Windows (well, NTFS).

The relevant bit of the stacktrace is:

```
[error] java.lang.UnsupportedOperationException
[error]         at java.base/java.nio.file.Files.setPosixFilePermissions(Files.java:2168)
[error]         at org.webjars.WebJarExtractor.extractResource(WebJarExtractor.java:147)
[error]         at org.webjars.WebJarExtractor.lambda$extractResourcesTo$0(WebJarExtractor.java:131)
[error]         at io.github.classgraph.ResourceList.forEachInputStreamIgnoringIOException(ResourceList.java:527)
[error]         at org.webjars.WebJarExtractor.extractResourcesTo(WebJarExtractor.java:131)
[error]         at org.webjars.WebJarExtractor.extractWebJarsTo(WebJarExtractor.java:179)
[error]         at org.webjars.WebJarExtractor.extractAllWebJarsTo(WebJarExtractor.java:64)
```

This is trying to transfer POSIX file permissions from a webjar `Resource` to the extracted file on the filesystem. I think the webjar `Resource` has POSIX file permissions (perhaps because it's in a zip??), but the extracted file is on NTFS which doesn't support POSIX permissions. The same code works fine on MacOS on APFS. It would probably fail on Mac/Linux on top of exFAT or FAT32, but I haven't tested that.

A possible (though maybe inefficient) fix could be to check whether the filesystem supports POSIX before setting permissions - a change to WebJarExtractor#146 something like:

```
      if (resourcePerms != null && Files.getFileStore(newFile.toPath).supportsFileAttributeView(PosixFileAttributeView.class)) {
        Files.setPosixFilePermissions(newFile.toPath(), resourcePerms);
      }
```

Impact of this is that it's not possible to use webjars on Play 2.9 on a non-POSIX filesystem (i.e. mostly meaning on Windows)

**Comment by inigo** [comment]
That's great - thank you. I can confirm that this fixes the problem for me.
