### ISSUE TITLE
ZipFile error

### ISSUE THREAD

**Issue by dispalt** [webjars/webjars-locator-core#15]
I think this is probably more of a sbt issue than this particular project, but in case it isn't I wanted to bring it up here.  Basically there seems to be an issue with commons-compress where 1.9 inherits from Closeable but 1.6 doesn't.  However, even if I play around with dependencyTree it still doesn't work.

```
[fundedby]> reload plugins
[info] Loading global plugins from /Users/dan/.yadr/sbt/0.13/plugins
[info] Loading project definition from /w/fundedby/project
> dependencyTree
...
[info]   | +-org.apache.commons:commons-compress:1.4.1 (evicted by: 1.9)
[info]   | +-org.apache.commons:commons-compress:1.6 (evicted by: 1.9)
[info]   | | +-org.tukaani:xz:1.4
[info]   | |
[info]   | +-org.apache.commons:commons-compress:1.9
...
```

```
[fundedby]> web-assets:webNodeModules
Cleaning up unclosed ZipFile for archive /Users/dan/.ivy2/cache/org.webjars/envjs/jars/envjs-1.2.jar
[error] ({.}/web-plugin:webJarsNodeModules) java.lang.IncompatibleClassChangeError: Class org.apache.commons.compress.archivers.zip.ZipFile does not implement the requested interface java.io.Closeable
[error] Total time: 1 s, completed Sep 26, 2016 11:26:22 PM
[fundedby]> last
[debug] Other repositories:
[debug] Default repositories:
[debug] Using inline dependencies specified in Scala.
[debug] [naha]
[debug] [naha] Initial source changes:
[debug] [naha] 	removed:Set()
[debug] [naha] 	added: Set()
[debug] [naha] 	modified: Set()
[debug] [naha] Invalidated products: Set()
[debug] [naha] External API changes: API Changes: Set()
[debug] [naha] Modified binary dependencies: Set()
[debug] [naha] Initial directly invalidated sources: Set()
[debug] [naha]
[debug] [naha] Sources indirectly invalidated by:
[debug] [naha] 	product: Set()
[debug] [naha] 	binary dep: Set()
[debug] [naha] 	external source: Set()
[debug] All initially invalidated sources: Set()
[debug] Copy resource mappings:
[debug]
[debug] Forcing garbage collection...
java.lang.IncompatibleClassChangeError: Class org.apache.commons.compress.archivers.zip.ZipFile does not implement the requested interface java.io.Closeable
       	at org.webjars.CloseQuietly.closeQuietly(CloseQuietly.java:20)
       	at org.webjars.WebJarExtractor.extractWebJarsTo(WebJarExtractor.java:139)
       	at org.webjars.WebJarExtractor.extractAllNodeModulesTo(WebJarExtractor.java:81)
       	at com.typesafe.sbt.web.SbtWeb$$anonfun$com$typesafe$sbt$web$SbtWeb$$generateNodeWebJars$1.apply(SbtWeb.scala:412)
       	at com.typesafe.sbt.web.SbtWeb$$anonfun$com$typesafe$sbt$web$SbtWeb$$generateNodeWebJars$1.apply(SbtWeb.scala:411)
       	at com.typesafe.sbt.web.SbtWeb$.withWebJarExtractor(SbtWeb.scala:404)
       	at com.typesafe.sbt.web.SbtWeb$.com$typesafe$sbt$web$SbtWeb$$generateNodeWebJars(SbtWeb.scala:410)
       	at com.typesafe.sbt.web.SbtWeb$$anonfun$38.apply(SbtWeb.scala:313)
       	at com.typesafe.sbt.web.SbtWeb$$anonfun$38.apply(SbtWeb.scala:313)
       	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
       	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
       	at sbt.std.Transform$$anon$4.work(System.scala:63)
       	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
       	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
       	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
       	at sbt.Execute.work(Execute.scala:237)
       	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
       	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
       	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
       	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
       	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
       	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
       	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
       	at java.lang.Thread.run(Thread.java:745)
[error] ({.}/web-plugin:webJarsNodeModules) java.lang.IncompatibleClassChangeError: Class org.apache.commons.compress.archivers.zip.ZipFile does not implement the requested interface java.io.Closeable
[error] Total time: 1 s, completed Sep 26, 2016 11:26:22 PM
```

**Comment by jamesward** [comment]
Hmmm... So you have `1.9` on the classpath but somehow it is still using `1.6`?  Is it possible that we are seeing the classpath for the sbt project instead of the root project?  Or vise versa?

**Comment by ddispaltro** [comment]
Yeah so here's the simplest example with it not working.  https://github.com/ddispaltro/sbt-sjs-issue

So it's something between sjs and sbt-web, can't figure out who's pulling in what though...

**Comment by jamesward** [comment]
Diving into this...

Check this out:
```
reload plugins

provided:dependencyTree

[info] default:project:0.1-SNAPSHOT [S]
[info]   +-org.scala-sbt:sbt:0.13.13-RC2 [S]
[info]     +-org.scala-sbt:main:0.13.13-RC2 [S]
[info]       +-org.scala-sbt:command:0.13.13-RC2 [S]
[info]       | +-org.foundweekends.giter8:giter8_2.10:0.7.1 [S]
[info]       | |   +-org.eclipse.jgit:org.eclipse.jgit.pgm:3.7.0.201502260915-r
[info]       | |     +-org.apache.commons:commons-compress:1.6
```

Ok. So that is what is pulling in `org.apache.commons:commons-compress:1.6`.  Now I just need to figure out how to override it.

**Comment by dispalt** [comment]
So it was an issue with an RC of 13.13, check this out.  Sorry I should have followed up.

https://github.com/sbt/sbt/issues/2761

**Comment by jamesward** [comment]
Ah cool.  Thanks!
