### ISSUE TITLE
NullPointerException from WebJarAssetLocator.getFullPathExact(…) 

### ISSUE THREAD

**Issue by odrotbohm** [webjars/webjars-locator-core#32]
I get this from a Spring Boot (2.2 snapshots) application using WebJars Locator Core in version 0.40:

```
Caused by: java.lang.NullPointerException: null
	at org.webjars.WebJarAssetLocator.getFullPathExact(WebJarAssetLocator.java:262)
	at org.springframework.web.servlet.resource.WebJarsResourceResolver.findWebJarResourcePath(WebJarsResourceResolver.java:109)
	at org.springframework.web.servlet.resource.WebJarsResourceResolver.resolveUrlPathInternal(WebJarsResourceResolver.java:94)
```

This did not occur in 0.38. Anything else I can provide to help investigating this issue?

**Comment by odrotbohm** [comment]
After a quick inspection, it looks like the code doesn't guard against the map lookup returning `null`:

```
if (allWebJars.get(webJarName).contents.contains(fullPath)) {
          //   ^ this could be null
```

Line 262 in 0.40.

**Comment by jamesward** [comment]
Ouch.  Thanks for reporting!  Yeah, I can get that fixed asap.

**Comment by jamesward** [comment]
0.41 is on it's way out and should fix this.

**Comment by odrotbohm** [comment]
No worries, James. Thanks for getting on top of that so quickly! 👍
